# Generated by Django 4.0.5 on 2022-08-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='celebrity_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrity_name', models.CharField(max_length=10)),
                ('celebrity_price', models.CharField(max_length=5)),
                ('celebrity_tag', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('upload', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
