# Generated by Django 4.0.5 on 2022-08-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_celebrity_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='celebrity_data',
            new_name='celebrity',
        ),
    ]
