# Generated by Django 4.0.5 on 2022-08-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_booking_delete_login_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='bookings',
        ),
    ]
