# Generated by Django 4.0.5 on 2022-08-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_rename_booking_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Name',
            field=models.CharField(max_length=40),
        ),
    ]
