# Generated by Django 4.0.5 on 2022-08-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_bookings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Occasion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='To',
            field=models.CharField(max_length=50),
        ),
    ]
